---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    project: default
    repoURL: https://github.com/snehagupta-coder/argo-workflow-demo.git
    targetRevision: HEAD
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
