apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: rollout
spec:
  serviceAccountName: workflow
  templates:
  - name: git-merge
    inputs:
      parameters:
      - name: environment
      - name: repo_owner
      - name: repo_name
      - name: branch
    script:
      image: alpine/git:v2.36.1
      command: [sh]
      source: |
        set -e
        git clone https://$(cat /.github/token)@github.com/{{inputs.parameters.repo_owner}}/{{inputs.parameters.repo_name}}
        sleep 2
        cd {{inputs.parameters.repo_name}}
        git config user.name "$(cat /.github/user)"
        git config user.email "$(cat /.github/email)"
        git branch origin/dev -f
        git checkout -b {{inputs.parameters.branch}}
        git pull origin {{inputs.parameters.branch}}
        git push origin {{inputs.parameters.branch}}
      volumeMounts:
      - name: github-access
        mountPath: /.github/
