apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample-applicationset
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - list:
      elements:
      - env: dev
      - env: stg
      - env: prd
  template:
    metadata:
      name: 'sample-application-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/snehagupta-coder/argo-workflow-demo.git
        targetRevision: '{{env}}'
        path: dummy-app
      destination:
        server: https://kubernetes.default.svc
        namespace: dummy-app-{{env}}