apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: workflows
    repoURL: https://github.com/snehagupta-coder/argo-workflow-demo.git
    targetRevision: HEAD
  destination:
    namespace: argo
    server:  https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

