apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    project: default
    path: argo-events
    repoURL: https://github.com/snehagupta-coder/argo-workflow-demo.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
