---

apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: github
    eventSourceName: github
    eventName: argo-workflow-demo
  triggers:
  - template:
      name: trigger
      argoWorkflow:
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: argo-workflow-demo-
              namespace: workflows
            spec:
              entrypoint: rollout
              serviceAccountName: workflow
              volumes:
              - name: github-access
                secret:
                  secretName: github-access
                  items:
                    - key: token
                      path: token
                    - key: user
                      path: user
                    - key: email
                      path: email
              templates:
              - name: rollout
                dag:
                  tasks:
                  - name: rollout-dev
                    templateRef:
                      name: rollout
                      template: git-merge
                      clusterScope: true
                    arguments:
                      parameters:
                      - name: environment
                        value: dev
                      - name: repo_owner
                        value: snehagupta-coder
                      - name: repo_name
                        value: argo-workflow-demo
                      - name: branch
                        value: dev
                  - name: validate-dev
                    container:
                      image: alpine:3.16.0
                      command: [sleep, "1m"]
                    dependencies:
                    - rollout-dev
                  - name: rollout-stg
                    templateRef:
                      name: rollout
                      template: git-merge
                      clusterScope: true
                    arguments:
                      parameters:
                      - name: environment
                        value: stg
                      - name: repo_owner
                        value: snehagupta-coder
                      - name: repo_name
                        value: argo-workflow-demo
                      - name: branch
                        value: stg
                    dependencies:
                    - velidate-dev
                  - name: validate-stg
                    container:
                      image: alpine:3.16.0
                      command: [sleep, "1m"]
                    dependencies:
                    - rollout-stg
                  - name: rollout-prd
                    templateRef:
                      name: rollout
                      template: git-merge
                      clusterScope: true
                    arguments:
                      parameters:
                      - name: environment
                        value: prd
                      - name: repo_owner
                        value: snehagupta-coder
                      - name: repo_name
                        value: argo-workflow-demo
                      - name: branch
                        value: prd
                    dependencies:
                    - validate-stg

