apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-token
  namespace: argo-events
spec:
  encryptedData:
    token: AgAyJpuYtcr5cauidwZ6rGPiNRK8r5Z0PAOJgz+KUfIQZoh4Q7x30eun2pOA8X5WcNb8nLQFX4fmJRuz8jlQCn2tqEW5tRpDf1j5E2HUy6PDGzGoehZJwzXe22r78fkBtKmb9OGJUOAsOPdk9MlbDRS0CEaVY1bjfaUeUD09yHOrxxDxC14TIjmILr1eLUSbzsqOS2KYzN4B/xAJhPpOMg7ttE6d8yWbunt/cNh4nr6+ixS+fgCpgreSw2C4eQnNB+J57PwQGeji9pc2y0NjTppXUcs170kNad9rbHgogbgiLgbN4NRhoqFd3PG8hlC3KmhANzcKISONvMp0LbfkaVX/pGJWB3XKUwN7j+STtf0AQ5F5ZmvGGOfDJgrTfi721ZfPX0ewlfp74r4RSjZ5WX6Qu59rn2RXhNYqMtOt6DsBwzluCKGiY4CpXCyMP2WAvujM4usSN1mIkUwr0lqFuoHAZ6hlhu1q68IKhfVl9mKHe3A1kyH9Bp92SUPHa2ldTKF9l8Wc+VH/ZCXgQ2CJaC21qDjE96kv97PcP/V9LQXzdfVjaIAhi59WgFR6yXWQSATA5XDhAWbp5oAM5kZXVMEp9we+7whWbEV08LAEotrbnlKxjuiIDmankcZAQ0J31AGtYe0mKhDfylFVDI7xYIlyi2IsmJbdZsEt5vG4Gw/smiZ5fPNJzUCGOjExULL0Ht1mE3Uh4lune0Bl3/Ut5UPo
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: webhook-token
      namespace: argo-events
    type: Opaque

